/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;

/**
 *
 * @author ana
 */
public class EnemyView extends javax.swing.JPanel {
    LootView lootView;
    DamageView damageView;

    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        lootView = new LootView();
        damageView = new DamageView();

        LootPanel.add(lootView);
        DamagePanel.add(damageView);

        repaint();
        revalidate();
    }

    public void setEnemy(deepspace.EnemyToUI enemigo) {
        enemyName.setText(enemigo.getName());
        power.setText(Float.toString(enemigo.getAmmoPower()));
        shields.setText(Float.toString(enemigo.getShieldPower()));

        lootView.setLoot(enemigo.getLoot());
        damageView.setDamage(enemigo.getDamage());

        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyText = new javax.swing.JLabel();
        powerText = new javax.swing.JLabel();
        shieldText = new javax.swing.JLabel();
        enemyName = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        LootPanel = new javax.swing.JPanel();
        DamagePanel = new javax.swing.JPanel();

        enemyText.setText("Enemigo:");

        powerText.setText("Pontecia de fuego:");

        shieldText.setText("Capacidad defensiva:");

        enemyName.setText("jLabel1");

        power.setText("jLabel2");

        shields.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enemyText)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enemyName))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shieldText)
                                    .addComponent(powerText)))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(shields)
                                .addComponent(power)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(LootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemyText)
                    .addComponent(enemyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerText)
                    .addComponent(power))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shields)
                    .addComponent(shieldText))
                .addGap(18, 18, 18)
                .addComponent(LootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DamagePanel;
    private javax.swing.JPanel LootPanel;
    private javax.swing.JLabel enemyName;
    private javax.swing.JLabel enemyText;
    private javax.swing.JLabel power;
    private javax.swing.JLabel powerText;
    private javax.swing.JLabel shieldText;
    private javax.swing.JLabel shields;
    // End of variables declaration//GEN-END:variables
}
