/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import static View.GUI.MainWindow.controller;
import deepspace.*;
import java.util.ArrayList;
import java.awt.Component;

/**
 *
 * @author ana
 */
public class StationView extends javax.swing.JPanel {

    HangarView hangar;

    /**
     * Creates new form StationView
     */
    public StationView() {
        initComponents();
        hangar = new HangarView();
        jpHangar.add(hangar);
        repaint();
        revalidate();
    }

    public void setStationView(SpaceStationToUI station){
        jlShowName.setText(station.getName());
        jlShowFire.setText(Double.toString(station.getAmmoPower()));
        jlShowShields.setText(Double.toString(station.getShieldPower()));
        jlShowMedals.setText(Integer.toString(station.getnMedals()));
        jlShowFuel.setText(Double.toString(station.getFuelUnits()));
        jpPendingDamage.removeAll();
        if(station.getPendingDamage() != null){
            DamageView d = new DamageView();
            d.setDamage(station.getPendingDamage());
            jpPendingDamage.add(d);
        }

        jpWeapons.removeAll();
        jpShields.removeAll();

        if(station.getHangar() == null){
            jpHangar.setVisible(false);
            jbDescartarHangar.setEnabled(false);
        } else {
            hangar.setHangar(station.getHangar());
            jbDescartarHangar.setEnabled(true);
        }

        for (WeaponToUI w : station.getWeapons()){
            WeaponView wv = new WeaponView();
            wv.setWeapon(w);
            jpWeapons.add(wv);
        }

        for (ShieldToUI s : station.getShieldBoosters()){
            ShieldBoosterView sv = new ShieldBoosterView();
            sv.setShieldBooster(s);
            jpShields.add(sv);
        }

        GameState gs = controller.getState();
        if (gs == GameState.INIT){
            jbMontar.setEnabled(true);
        }
        else if (gs == GameState.BEFORECOMBAT){
            jbMontar.setEnabled(false);
        }
        else if (gs== GameState.AFTERCOMBAT){
            jbMontar.setEnabled(true);
        }

        repaint();
        revalidate();
    }

    public ArrayList<Integer> getSelectedWeapons(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : jpWeapons.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    }

    public ArrayList<Integer> getSelectedShields(){
        ArrayList<Integer> selected = new ArrayList();
        int i = 0;
        for (Component c : jpShields.getComponents()) {
            if (((CombatElementView) c).isSelected()) {
                selected.add(i);
            }
            i++;
        }
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlname = new javax.swing.JLabel();
        jlfire = new javax.swing.JLabel();
        jlshields = new javax.swing.JLabel();
        jlShowName = new javax.swing.JLabel();
        jlShowFire = new javax.swing.JLabel();
        jlShowShields = new javax.swing.JLabel();
        jlMedals = new javax.swing.JLabel();
        jlFuel = new javax.swing.JLabel();
        jlShowMedals = new javax.swing.JLabel();
        jlShowFuel = new javax.swing.JLabel();
        jScrollWeapons = new javax.swing.JScrollPane();
        jpWeapons = new javax.swing.JPanel();
        jScrollShields = new javax.swing.JScrollPane();
        jpShields = new javax.swing.JPanel();
        jpPendingDamage = new javax.swing.JPanel();
        jbMontar = new javax.swing.JButton();
        jbDescartar = new javax.swing.JButton();
        jbDescartarHangar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpHangar = new javax.swing.JPanel();

        jlname.setText("Nombre: ");

        jlfire.setText("Fuego: ");

        jlshields.setText("Escudos: ");

        jlShowName.setText("jLabel4");

        jlShowFire.setText("jLabel5");

        jlShowShields.setText("jLabel6");

        jlMedals.setText("Medallas:");

        jlFuel.setText("Combustible: ");

        jlShowMedals.setText("jLabel9");

        jlShowFuel.setText("jLabel10");

        jpWeapons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollWeapons.setViewportView(jpWeapons);

        jpShields.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollShields.setViewportView(jpShields);

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbMontar.setText("Montar");
        jbMontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMontarActionPerformed(evt);
            }
        });

        jbDescartar.setText("Descartar");
        jbDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDescartarActionPerformed(evt);
            }
        });

        jbDescartarHangar.setText("Descartar hangar");
        jbDescartarHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDescartarHangarActionPerformed(evt);
            }
        });

        jpHangar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jpHangar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jbMontar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDescartar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDescartarHangar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlfire)
                                            .addComponent(jlshields))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlShowShields)
                                            .addComponent(jlShowFire)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jlname)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlShowName)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlFuel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlShowFuel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlMedals)
                                        .addGap(48, 48, 48)
                                        .addComponent(jlShowMedals)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlname)
                    .addComponent(jlShowName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfire)
                    .addComponent(jlShowFire)
                    .addComponent(jlMedals)
                    .addComponent(jlShowMedals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlshields)
                    .addComponent(jlShowShields)
                    .addComponent(jlFuel)
                    .addComponent(jlShowFuel))
                .addGap(18, 18, 18)
                .addComponent(jScrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMontar)
                    .addComponent(jbDescartar)
                    .addComponent(jbDescartarHangar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbMontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMontarActionPerformed
        // TODO add your handling code here:
        MainWindow.controller.mountCombatElements(hangar.getSelected());
        repaint();
        revalidate();
    }//GEN-LAST:event_jbMontarActionPerformed

    private void jbDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDescartarActionPerformed
        // TODO add your handling code here:
        MainWindow.controller.discardCombatElements(hangar.getSelected(), getSelectedWeapons(), getSelectedShields());
        repaint();
        revalidate();
    }//GEN-LAST:event_jbDescartarActionPerformed

    private void jbDescartarHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDescartarHangarActionPerformed
        // TODO add your handling code here:
        MainWindow.controller.discardHangar();
        repaint();
        revalidate();
    }//GEN-LAST:event_jbDescartarHangarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollShields;
    private javax.swing.JScrollPane jScrollWeapons;
    private javax.swing.JButton jbDescartar;
    private javax.swing.JButton jbDescartarHangar;
    private javax.swing.JButton jbMontar;
    private javax.swing.JLabel jlFuel;
    private javax.swing.JLabel jlMedals;
    private javax.swing.JLabel jlShowFire;
    private javax.swing.JLabel jlShowFuel;
    private javax.swing.JLabel jlShowMedals;
    private javax.swing.JLabel jlShowName;
    private javax.swing.JLabel jlShowShields;
    private javax.swing.JLabel jlfire;
    private javax.swing.JLabel jlname;
    private javax.swing.JLabel jlshields;
    private javax.swing.JPanel jpHangar;
    private javax.swing.JPanel jpPendingDamage;
    private javax.swing.JPanel jpShields;
    private javax.swing.JPanel jpWeapons;
    // End of variables declaration//GEN-END:variables
}
