/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.WeaponToUI;

/**
 *
 * @author ana
 */
public class WeaponView extends javax.swing.JPanel implements CombatElementView{

    private boolean selected = false;

    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }

    public boolean isSelected(){
        return selected;
    }

    void setWeapon(WeaponToUI weap){
        jldisplayusos.setText(Integer.toString(weap.getUses()));
        jldisplaypotencia.setText(Float.toString(weap.getPower()));
        if(weap.getType() == deepspace.WeaponType.LASER)
            jldisplaytipo.setText("LASER");
        if(weap.getType()==deepspace.WeaponType.MISSILE)
            jldisplaytipo.setText("MISSILE");
        if(weap.getType()==deepspace.WeaponType.PLASMA)
            jldisplaytipo.setText("PLASMA");
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jltipo = new javax.swing.JLabel();
        jlpotencia = new javax.swing.JLabel();
        jlusos = new javax.swing.JLabel();
        jldisplaytipo = new javax.swing.JLabel();
        jldisplaypotencia = new javax.swing.JLabel();
        jldisplayusos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 242, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jltipo.setText("Tipo:");

        jlpotencia.setText("Potencia:");

        jlusos.setText("Usos:");

        jldisplaytipo.setText("jLabel1");

        jldisplaypotencia.setText("jLabel2");

        jldisplayusos.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlusos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jldisplayusos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlpotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jldisplaypotencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jltipo)
                        .addGap(55, 55, 55)
                        .addComponent(jldisplaytipo)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltipo)
                    .addComponent(jldisplaytipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpotencia)
                    .addComponent(jldisplaypotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlusos)
                    .addComponent(jldisplayusos))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jldisplaypotencia;
    private javax.swing.JLabel jldisplaytipo;
    private javax.swing.JLabel jldisplayusos;
    private javax.swing.JLabel jlpotencia;
    private javax.swing.JLabel jltipo;
    private javax.swing.JLabel jlusos;
    // End of variables declaration//GEN-END:variables
}
